# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20181205_1802'),
        ('usergroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='contests',
            field=models.ManyToManyField(blank=True, to='contests.Contest'),
        ),
    ]
